warning("Please manually run the code line by line and save the image from the preview box.")
source("00.Functions.R")
CheckPackage(c("readxl"))
# First we need to get the cutoff value.
source("01.CalculateCutoff.R")
OrginalData.TCGA$Group = ifelse(OrginalData.TCGA$prec.TIL > res.cut.TCGA$prec.TIL$estimate, "High TIL", "Low TIL")
pdf(file = "TCGA.TIL.OS.PDF", width = 6, height = 6)
Plot.KM(OrginalData.TCGA, title = "prec.TIL")
dev.off()
OrginalData.TCGA$Group = ifelse(OrginalData.TCGA$prec.TLS > res.cut.TCGA$prec.TLS$estimate, "High TLS", "Low TLS")
pdf(file = "TCGA.TLS.OS.PDF", width = 6, height = 6)
Plot.KM(OrginalData.TCGA, title = "prec.TLS")
dev.off()

OrginalData.XJH$Group = ifelse(OrginalData.XJH$prec.TIL > res.cut.TCGA$prec.TIL$estimate, "High TIL", "Low TIL")
pdf(file = "XJH.TIL.OS.PDF", width = 6, height = 6)
Plot.KM(OrginalData.XJH, title = "prec.TIL - XJH")
dev.off()
OrginalData.XJH$Group = ifelse(OrginalData.XJH$prec.TLS > res.cut.TCGA$prec.TLS$estimate, "High TLS", "Low TLS")
pdf(file = "XJH.TLS.OS.PDF", width = 6, height = 6)
Plot.KM(OrginalData.XJH, title = "prec.TLS - XJH")
dev.off()
